fixtures:
  repositories:
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql"
    vcsrepo: "git://github.com/puppetlabs/puppetlabs-vcsrepo"
    concat: "git://github.com/puppetlabs/puppetlabs-concat"
    apache: "git://github.com/puppetlabs/puppetlabs-apache"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
  symlinks:
    redmine: "#{source_dir}"
