fixtures:
  repositories:
    apache: "git://github.com/johanek/johanek-apache.git"
    passenger: "git://github.com/johanek/johanek-passenger.git"
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
  symlinks:
    redmine: "#{source_dir}"
